import {ENV} from "../env";

export const BASE_URL = ENV.BASE_URL;
export const BASE_URL_FRONTEND = ENV.BASE_URL_FRONTEND;
export const USER_MANAGEMENT_SYSTEM_BACKEND_URL = ENV.USER_MANAGEMENT_SYSTEM_BACKEND_URL;
export const USER_MANAGEMENT_SYSTEM_FRONTEND_URL = ENV.USER_MANAGEMENT_SYSTEM_FRONTEND_URL;

export const APP_KEY = ENV.APP_KEY;

export const LP_APP_ID = ENV.LP_APP_ID;
export const LP_APP_ROLE_ID = ENV.LP_APP_ROLE_ID;
export const UMS_ROLE_ID = ENV.UMS_ROLE_ID;
export const VENDOR_APP_ID = ENV.VENDOR_APP_ID;
export const CUSTOMER_APP_ID = ENV.CUSTOMER_APP_ID;

export const HELP_ME_API = ENV.HELP_ME_API;
export const ROLE_NAME = ENV.ROLE_NAME;

export const LP_FRONTEND_URL = ENV.BASE_URL_FRONTEND




