export const ENV = {
    BASE_URL: process.env.VUE_APP_LP_BACKEND_BASE_URL,
    BASE_URL_FRONTEND: process.env.VUE_APP_LP_FRONTEND_BASE_URL,
    LP_APP_ID: process.env.VUE_APP_LP_APP_ID,
    LP_APP_ROLE_ID: process.env.VUE_APP_LP_APP_ROLE_ID,
    UMS_ROLE_ID: process.env.VUE_APP_UMS_ROLE_ID,
    VENDOR_APP_ID: process.env.VUE_APP_LP_VENDOR_APP_ID,
    CUSTOMER_APP_ID: process.env.VUE_APP_LP_CUSTOMER_APP_ID,
    USER_MANAGEMENT_SYSTEM_BACKEND_URL: process.env.VUE_APP_USER_MANAGEMENT_SYSTEM_BACKEND_URL,
    USER_MANAGEMENT_SYSTEM_FRONTEND_URL: process.env.VUE_APP_USER_MANAGEMENT_SYSTEM_FRONTEND_URL,
    APP_KEY: process.env.VUE_APP_LP_APPLICATION_KEY,
    HELP_ME_API: process.env.VUE_APP_HELPME_API,
    AUTH_KEY: 'id_token',
    USER_DATA: 'user_data',
    UMS_USER_DATA: 'ums_user_data',
    APP_INFO: 'app_info',
    APP_CURRENCY: 'app_currency',
    ROLE_NAME: 'user',
    ADMIN: 'admin',
    ALL_APPS: 'app_apps',
};
